name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --all-groups

      - name: Build wheel
        run: uv build

      - name: Publish package
        env:
          # UV_PUBLISH_URL is not needed here; it defaults to PyPI
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish